function [ timeStr ] = getTimeStamp()
%GETTIMESTAMP Get time stamp in string
  c = clock;
  timeStr = [sprintf('%04d', c(1)), ...
             sprintf('%02d', c(2)), ...
             sprintf('%02d', c(3)), ...
             sprintf('%02d', c(4)), ...
             sprintf('%02d', c(5)), ...
             sprintf('%02d', floor(c(6)))];
end

